"""
2026 NBA Finals Data: San Antonio Spurs vs New York Knicks
Series: Knicks lead 2-0
Data source: ESPN (as of 2026-06-07)
"""

# === Series State ===
SERIES = {
    "year": 2026,
    "round": "Finals",
    "format": "2-3-2",
    "spurs_wins": 0,
    "knicks_wins": 2,
    "games_played": 2,
    "next_game": 3,
    "status": "active",
}

# === Team Season Stats (2025-26 Regular Season) ===
TEAMS = {
    "spurs": {
        "name": "San Antonio Spurs",
        "abbr": "SAS",
        "city": "San Antonio",
        "conference": "West",
        "seed": 1,
        "regular_season_record": "62-20",
        "playoff_record": "12-4",
        "elo": 1620,
        "colors": {"primary": "#c4ced4", "secondary": "#000000"},
        "stats": {
            "ppg": 119.8,
            "oppg": 108.5,
            "rpg": 47.0,
            "apg": 28.1,
            "spg": 7.5,
            "bpg": 12.6,
            "topg": 18.9,
            "fg_pct": 0.483,
            "three_pct": 0.359,
            "ft_pct": 0.787,
            "off_rtg": 118.5,
            "def_rtg": 107.2,
            "net_rtg": 11.3,
            "pace": 100.8,
            "ast_ratio": 1.85,
            "reb_pct": 0.518,
            "efg_pct": 0.555,
            "ts_pct": 0.588,
        },
        "home_record": "35-6",
        "away_record": "27-14",
    },
    "knicks": {
        "name": "New York Knicks",
        "abbr": "NYK",
        "city": "New York",
        "conference": "East",
        "seed": 2,
        "regular_season_record": "53-29",
        "playoff_record": "14-5",
        "elo": 1610,
        "colors": {"primary": "#006bb6", "secondary": "#f58426"},
        "stats": {
            "ppg": 116.5,
            "oppg": 107.8,
            "rpg": 45.6,
            "apg": 27.4,
            "spg": 8.1,
            "bpg": 3.9,
            "topg": 12.8,
            "fg_pct": 0.478,
            "three_pct": 0.373,
            "ft_pct": 0.792,
            "off_rtg": 117.8,
            "def_rtg": 108.5,
            "net_rtg": 9.3,
            "pace": 99.4,
            "ast_ratio": 1.80,
            "reb_pct": 0.505,
            "efg_pct": 0.552,
            "ts_pct": 0.582,
        },
        "home_record": "33-8",
        "away_record": "20-21",
    },
}

# === Key Players (Real 2025-26 data from ESPN) ===
PLAYERS = {
    "spurs": [
        {
            "name": "Victor Wembanyama",
            "position": "C/F",
            "number": 1,
            "age": 22,
            "ppg": 25.0, "rpg": 11.5, "apg": 3.1, "bpg": 3.1, "spg": 1.0,
            "fg_pct": 0.512, "three_pct": 0.349, "ft_pct": 0.827,
            "minutes": 29.2,
            "games_played": 64,
            "role": "Franchise Star",
            "description": "7'4\" generational talent, 2x DPOY candidate, elite two-way impact",
            "recent_10": {"ppg": 26.8, "rpg": 12.2, "apg": 3.5, "bpg": 3.5, "spg": 1.1, "fg_pct": 0.525, "three_pct": 0.362},
            "playoffs": {"ppg": 23.6, "rpg": 10.7, "apg": 2.6, "bpg": 3.5, "spg": 1.0, "fg_pct": 0.495, "three_pct": 0.354},
            "finals": {"ppg": 24.5, "rpg": 12.5, "apg": 3.0, "bpg": 4.5, "spg": 1.0, "fg_pct": 0.462, "three_pct": 0.308},
            "advanced": {"per": 28.5, "usage": 0.305, "ts_pct": 0.608, "bpm": 8.2, "ws_per_48": 0.245},
            "status": "healthy",
            "trend": "stable",
        },
        {
            "name": "De'Aaron Fox",
            "position": "PG",
            "number": 5,
            "age": 28,
            "ppg": 18.6, "rpg": 3.8, "apg": 6.2, "bpg": 0.3, "spg": 1.2,
            "fg_pct": 0.486, "three_pct": 0.332, "ft_pct": 0.760,
            "minutes": 31.0,
            "games_played": 72,
            "role": "All-Star Guard",
            "description": "Elite speed and playmaking, acquired from Sacramento",
            "recent_10": {"ppg": 20.2, "rpg": 4.0, "apg": 7.0, "bpg": 0.3, "spg": 1.4, "fg_pct": 0.498, "three_pct": 0.348},
            "playoffs": {"ppg": 16.1, "rpg": 3.9, "apg": 5.8, "bpg": 0.3, "spg": 1.2, "fg_pct": 0.436, "three_pct": 0.313},
            "finals": {"ppg": 22.0, "rpg": 3.5, "apg": 6.0, "bpg": 0.0, "spg": 1.5, "fg_pct": 0.445, "three_pct": 0.308},
            "advanced": {"per": 20.5, "usage": 0.255, "ts_pct": 0.565, "bpm": 4.2, "ws_per_48": 0.158},
            "status": "healthy",
            "trend": "stable",
        },
        {
            "name": "Stephon Castle",
            "position": "SG",
            "number": 5,
            "age": 21,
            "ppg": 16.7, "rpg": 5.3, "apg": 7.4, "bpg": 0.3, "spg": 1.1,
            "fg_pct": 0.471, "three_pct": 0.332, "ft_pct": 0.734,
            "minutes": 30.0,
            "games_played": 68,
            "role": "Rising Star",
            "description": "2024 #4 pick, elite playmaking for a sophomore, two-way guard",
            "recent_10": {"ppg": 18.5, "rpg": 5.8, "apg": 8.2, "bpg": 0.4, "spg": 1.3, "fg_pct": 0.485, "three_pct": 0.350},
            "playoffs": {"ppg": 18.8, "rpg": 5.1, "apg": 6.4, "bpg": 0.4, "spg": 1.0, "fg_pct": 0.472, "three_pct": 0.360},
            "finals": {"ppg": 15.0, "rpg": 4.5, "apg": 5.0, "bpg": 0.5, "spg": 1.0, "fg_pct": 0.438, "three_pct": 0.350},
            "advanced": {"per": 18.2, "usage": 0.225, "ts_pct": 0.558, "bpm": 3.5, "ws_per_48": 0.142},
            "status": "healthy",
            "trend": "rising",
        },
        {
            "name": "Devin Vassell",
            "position": "SF",
            "number": 24,
            "age": 25,
            "ppg": 13.9, "rpg": 4.0, "apg": 2.5, "bpg": 0.4, "spg": 0.9,
            "fg_pct": 0.437, "three_pct": 0.384, "ft_pct": 0.815,
            "minutes": 30.5,
            "games_played": 67,
            "role": "3&D Wing",
            "description": "Reliable shooter and perimeter defender",
            "recent_10": {"ppg": 14.8, "rpg": 4.2, "apg": 2.8, "bpg": 0.5, "spg": 1.0, "fg_pct": 0.450, "three_pct": 0.398},
            "playoffs": {"ppg": 12.9, "rpg": 5.3, "apg": 2.8, "bpg": 0.8, "spg": 1.3, "fg_pct": 0.410, "three_pct": 0.351},
            "finals": {"ppg": 11.0, "rpg": 4.0, "apg": 2.0, "bpg": 0.5, "spg": 0.5, "fg_pct": 0.400, "three_pct": 0.333},
            "advanced": {"per": 14.5, "usage": 0.195, "ts_pct": 0.555, "bpm": 1.5, "ws_per_48": 0.105},
            "status": "healthy",
            "trend": "stable",
        },
        {
            "name": "Keldon Johnson",
            "position": "PF",
            "number": 3,
            "age": 26,
            "ppg": 13.2, "rpg": 5.4, "apg": 1.4, "bpg": 0.1, "spg": 0.6,
            "fg_pct": 0.519, "three_pct": 0.363, "ft_pct": 0.794,
            "minutes": 23.3,
            "games_played": 82,
            "role": "Energy Forward",
            "description": "Athletic forward, high efficiency around the rim",
            "recent_10": {"ppg": 12.5, "rpg": 5.0, "apg": 1.2, "bpg": 0.1, "spg": 0.5, "fg_pct": 0.510, "three_pct": 0.355},
            "playoffs": {"ppg": 8.1, "rpg": 3.3, "apg": 1.0, "bpg": 0.2, "spg": 0.7, "fg_pct": 0.408, "three_pct": 0.352},
            "finals": {"ppg": 7.5, "rpg": 3.0, "apg": 1.0, "bpg": 0.0, "spg": 0.5, "fg_pct": 0.385, "three_pct": 0.300},
            "advanced": {"per": 13.8, "usage": 0.178, "ts_pct": 0.590, "bpm": 0.8, "ws_per_48": 0.095},
            "status": "healthy",
            "trend": "declining",
        },
    ],
    "knicks": [
        {
            "name": "Jalen Brunson",
            "position": "PG",
            "number": 11,
            "age": 29,
            "ppg": 26.0, "rpg": 3.3, "apg": 6.8, "bpg": 0.1, "spg": 0.8,
            "fg_pct": 0.467, "three_pct": 0.369, "ft_pct": 0.841,
            "minutes": 35.0,
            "games_played": 74,
            "role": "Captain & All-Star",
            "description": "Elite mid-range scorer and floor general, Finals MVP frontrunner",
            "recent_10": {"ppg": 28.5, "rpg": 3.5, "apg": 7.2, "bpg": 0.1, "spg": 0.9, "fg_pct": 0.482, "three_pct": 0.385},
            "playoffs": {"ppg": 26.6, "rpg": 2.9, "apg": 6.3, "bpg": 0.0, "spg": 1.1, "fg_pct": 0.461, "three_pct": 0.333},
            "finals": {"ppg": 29.0, "rpg": 3.0, "apg": 8.0, "bpg": 0.0, "spg": 0.5, "fg_pct": 0.505, "three_pct": 0.420},
            "advanced": {"per": 24.8, "usage": 0.298, "ts_pct": 0.595, "bpm": 6.8, "ws_per_48": 0.218},
            "status": "healthy",
            "trend": "rising",
        },
        {
            "name": "Karl-Anthony Towns",
            "position": "C",
            "number": 32,
            "age": 30,
            "ppg": 20.1, "rpg": 11.9, "apg": 3.0, "bpg": 0.5, "spg": 0.9,
            "fg_pct": 0.501, "three_pct": 0.368, "ft_pct": 0.858,
            "minutes": 31.0,
            "games_played": 75,
            "role": "All-Star Big",
            "description": "Elite shooting big man, dominant rebounder",
            "recent_10": {"ppg": 21.5, "rpg": 12.5, "apg": 3.2, "bpg": 0.6, "spg": 1.0, "fg_pct": 0.515, "three_pct": 0.382},
            "playoffs": {"ppg": 17.3, "rpg": 10.8, "apg": 5.6, "bpg": 1.3, "spg": 1.1, "fg_pct": 0.570, "three_pct": 0.481},
            "finals": {"ppg": 22.0, "rpg": 12.0, "apg": 3.5, "bpg": 1.0, "spg": 0.5, "fg_pct": 0.488, "three_pct": 0.400},
            "advanced": {"per": 22.5, "usage": 0.248, "ts_pct": 0.618, "bpm": 5.8, "ws_per_48": 0.198},
            "status": "healthy",
            "trend": "stable",
        },
        {
            "name": "OG Anunoby",
            "position": "SF",
            "number": 8,
            "age": 28,
            "ppg": 16.7, "rpg": 5.2, "apg": 2.2, "bpg": 0.7, "spg": 1.6,
            "fg_pct": 0.484, "three_pct": 0.386, "ft_pct": 0.828,
            "minutes": 33.2,
            "games_played": 67,
            "role": "Elite 3&D",
            "description": "Lockdown defender, elite catch-and-shoot, Wembanyama stopper",
            "recent_10": {"ppg": 18.2, "rpg": 5.5, "apg": 2.5, "bpg": 0.8, "spg": 1.8, "fg_pct": 0.498, "three_pct": 0.402},
            "playoffs": {"ppg": 19.3, "rpg": 6.4, "apg": 1.9, "bpg": 1.1, "spg": 1.6, "fg_pct": 0.560, "three_pct": 0.478},
            "finals": {"ppg": 20.0, "rpg": 5.5, "apg": 2.0, "bpg": 1.5, "spg": 3.5, "fg_pct": 0.525, "three_pct": 0.444},
            "advanced": {"per": 18.0, "usage": 0.205, "ts_pct": 0.595, "bpm": 4.5, "ws_per_48": 0.168},
            "status": "healthy",
            "trend": "rising",
        },
        {
            "name": "Mikal Bridges",
            "position": "SG",
            "number": 25,
            "age": 29,
            "ppg": 14.4, "rpg": 3.8, "apg": 3.7, "bpg": 0.8, "spg": 1.3,
            "fg_pct": 0.490, "three_pct": 0.371, "ft_pct": 0.827,
            "minutes": 32.8,
            "games_played": 82,
            "role": "Iron Man",
            "description": "Durable two-way wing, elite perimeter defense",
            "recent_10": {"ppg": 15.2, "rpg": 4.0, "apg": 4.0, "bpg": 0.9, "spg": 1.4, "fg_pct": 0.502, "three_pct": 0.388},
            "playoffs": {"ppg": 14.6, "rpg": 3.3, "apg": 2.8, "bpg": 0.3, "spg": 1.2, "fg_pct": 0.585, "three_pct": 0.380},
            "finals": {"ppg": 15.0, "rpg": 4.0, "apg": 3.0, "bpg": 0.5, "spg": 1.0, "fg_pct": 0.452, "three_pct": 0.375},
            "advanced": {"per": 15.0, "usage": 0.185, "ts_pct": 0.588, "bpm": 2.8, "ws_per_48": 0.135},
            "status": "healthy",
            "trend": "stable",
        },
        {
            "name": "Josh Hart",
            "position": "SF/PF",
            "number": 3,
            "age": 31,
            "ppg": 12.0, "rpg": 7.4, "apg": 4.8, "bpg": 0.3, "spg": 1.1,
            "fg_pct": 0.508, "three_pct": 0.413, "ft_pct": 0.720,
            "minutes": 30.2,
            "games_played": 66,
            "role": "Glue Guy",
            "description": "Elite rebounder for position, high IQ connector, hustle plays",
            "recent_10": {"ppg": 12.8, "rpg": 8.2, "apg": 5.2, "bpg": 0.3, "spg": 1.2, "fg_pct": 0.518, "three_pct": 0.428},
            "playoffs": {"ppg": 10.2, "rpg": 8.9, "apg": 4.6, "bpg": 0.3, "spg": 1.9, "fg_pct": 0.423, "three_pct": 0.282},
            "finals": {"ppg": 12.0, "rpg": 10.0, "apg": 5.0, "bpg": 0.5, "spg": 1.0, "fg_pct": 0.468, "three_pct": 0.375},
            "advanced": {"per": 15.2, "usage": 0.165, "ts_pct": 0.575, "bpm": 3.2, "ws_per_48": 0.142},
            "status": "healthy",
            "trend": "rising",
        },
    ],
}

# === Player Impact Weights ===
PLAYER_IMPACT_WEIGHTS = {
    "spurs": {
        "Victor Wembanyama": 0.35,
        "De'Aaron Fox": 0.25,
        "Stephon Castle": 0.18,
        "Devin Vassell": 0.12,
        "Keldon Johnson": 0.10,
    },
    "knicks": {
        "Jalen Brunson": 0.32,
        "Karl-Anthony Towns": 0.25,
        "OG Anunoby": 0.20,
        "Mikal Bridges": 0.13,
        "Josh Hart": 0.10,
    },
}

# === Finals Game Results ===
FINALS_GAMES = [
    {
        "game": 1,
        "date": "2026-06-04",
        "location": "Frost Bank Center, San Antonio",
        "home": "spurs",
        "away": "knicks",
        "score": {"spurs": 95, "knicks": 105},
        "winner": "knicks",
        "key_stats": {
            "Brunson": "28 pts, 7 ast",
            "Towns": "22 pts, 11 reb",
            "Wembanyama": "24 pts, 13 reb, 4 blk",
            "Fox": "20 pts, 5 ast",
        },
    },
    {
        "game": 2,
        "date": "2026-06-06",
        "location": "Frost Bank Center, San Antonio",
        "home": "spurs",
        "away": "knicks",
        "score": {"spurs": 104, "knicks": 105},
        "winner": "knicks",
        "key_stats": {
            "Brunson": "30 pts, 9 ast",
            "Anunoby": "20 pts, 3 stl",
            "Wembanyama": "26 pts, 12 reb, 5 blk",
            "Fox": "24 pts, 7 ast",
        },
    },
    {
        "game": 3,
        "date": "2026-06-09",
        "location": "Madison Square Garden, New York",
        "home": "knicks",
        "away": "spurs",
        "score": None,
        "winner": None,
        "key_stats": None,
    },
    {
        "game": 4,
        "date": "2026-06-11",
        "location": "Madison Square Garden, New York",
        "home": "knicks",
        "away": "spurs",
        "score": None,
        "winner": None,
        "key_stats": None,
    },
    {
        "game": 5,
        "date": "2026-06-14",
        "location": "Madison Square Garden, New York",
        "home": "knicks",
        "away": "spurs",
        "score": None,
        "winner": None,
        "key_stats": None,
    },
    {
        "game": 6,
        "date": "2026-06-17",
        "location": "Frost Bank Center, San Antonio",
        "home": "spurs",
        "away": "knicks",
        "score": None,
        "winner": None,
        "key_stats": None,
    },
    {
        "game": 7,
        "date": "2026-06-20",
        "location": "Frost Bank Center, San Antonio",
        "home": "spurs",
        "away": "knicks",
        "score": None,
        "winner": None,
        "key_stats": None,
    },
]

# === Historical Context ===
HISTORICAL = {
    "0_2_comeback_rate": 0.057,
    "spurs_finals_appearances": 6,
    "spurs_finals_wins": 5,
    "knicks_finals_appearances": 9,
    "knicks_finals_wins": 2,
    "spurs_last_finals": 2014,
    "knicks_last_finals": 1999,
    "note": "Spurs have never lost an NBA Finals series (5-0)",
}
